#!/bin/bash

R= "e\[31m"
G= "e\[32m"
N= "e\[0m"

USERID=$(id -u)

if [ $USERID -ne 0 ];then
    echo "ERROR :: Please enter the script in root access"
    exit 1
else
    echo "You are running in root access"
fi



VALIDATE()
{
    if [ $1 -eq 0 ];then
        echo "Installing $2 is .....$G SUCCESS $N"
    else
        echo "Installing $2 is .....$R FAILURE $N"
        exit 1
    fi
}

Package=("mysql" "nginx" "nodejs")

for i in ${Package[@]}
do
    dnf list installed $Package
    if [ $? -ne 0 ]; then
        echo "$Package is not installed going to install it"
        dnf install mysql -y
        VALIDATE $? $Package
    else
        echo "$Package is already installed"
    fi
done
  

