#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ];then
    echo "ERROR :: Please enter the script in root access"
    exit 1
else
    echo "You are running in root access"
fi

VALIDATE()
{
    if [ $1 -eq 0 ];then
        echo "Installing $2 is ..... SUCCESS"
    else
        echo "Installing $2 is ..... FAILURE"
        exit 1
    fi
}   


Install_Function(){
    dnf list installed $2
    if [ $1 -ne 0 ]; then
        echo "$2 is not installed going to install it"
        dnf install $2 -y
        VALIDATE $? "$2"
    else
        echo "$2 is already installed"
    fi
}

Install_Fucntion $? "nginx"
