#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ];then
    echo "ERROR :: Please enter the script in root access"
    exit 1
else
    echo "You are running in root access"

VALIDATE(){
    if [ $1 -eq 0 ];then
        echo "Installing $2 is ..... SUCCESS"
    else
        echo "Installing $2 is ..... FAILURE"
        exit 1
}

dnf list installed mysql

if [ $? -ne 0 ]; then
    echo "mysql is not installed going to install it"
    dnf install mysql -y
    VALIDATE $? "mysql"
else
    echo "mysql is already installed"