#!/bin/bash

USERID=$(id -u)

if [ $USERID -eq 0 ] 
then
    echo "You are running in root access"
     
else
    echo "ERROR:: Please run this script in root access"
    exit 1 #gives status code other than 0
fi

dnf list installed mysql

if [ $? -eq 0 ]
then 
    echo "Mysql is already installed"
else
    echo "Mysql is not yet installed"
    dnf install mysql -y

if [ $? -eq 0 ]
then 
    echo "Installing Mysql is....SUCCESS"
else
    echo "Installing Mysql is....FAILURE"
    exit 1 #gives status code other than 0
fi



# dnf list installed mysql

# if [ $? -eq 0 ]
# then 
#     echo "Mysql is already installed"
# else
#     echo "Mysql is not yet installed"
#     exit 1
# fi
