#!/bin/bash

user=$( id -u )

if [ $user -ne 0 ]
then 
    echo "you don't have root access to install mysql"
    
else
    echo "You are running in root access"
    exit 1

fi

dnf install mysql -y

if [ $? -eq 0 ]
then 
    echo "Your mysql installation is Success"
else
    echo "Your mysql installation Failed"

fi



