#!/bin/bash

user=$( id -u )

echo "exit code of status of user type is $user"

if [ $user -ne 0 ]
then 
    echo "you don't have root access to install mysql"
    exit 1

else
    echo "You are running in root access"
    

fi

dnf install mysql -y

echo "exit code of installation process $?"

if [ $? -eq 0 ]
then 
    echo "Your mysql installation is Success"
else
    echo "Your mysql installation Failed"

fi

dnf list installed mysql

echo "exit code of installation status of mysql is $?"


if [ $? -eq 0 ]
then 
    echo "You already have mysql installed"
else
    echo "You don't have mysql"

fi



