#!/bin/bash

# argfunction1() {
#     echo "i came from the input of 1st argument:: $1"
# }

# read -p "Enter arugment to be passed to function::" Argumentname

# argfunction1 "$Argumentname"


#!/bin/bash

my_function() {
    echo "I came from the input of 1st argument: $1"
}

# Example list of values

for i in {1..3}; do
    read -p "Enter argument to be passed $i::" arguments
    my_function "$arguments"
done
