#!/bin/bash

# argfunction1() {
#     echo "i came from the input of 1st argument:: $1"
# }

# read -p "Enter arugment to be passed to function::" Argumentname

# argfunction1 "$Argumentname"


#!/bin/bash

my_function() {
    echo "I came from the input of 1st argument: $1"
}

# Example list of values
arguments=read -p "Enter argument to be passed::"

for i in "${arguments[@]}"; do
    my_function "$i"
done
